### PR TITLE
Core Code

### LINKED ISSUE #3: core code
- [x] implement all operation listeners
- [x] proper handling of policy util
- [x] config handling with objects and use default configs provided by aerospike
- [x] give the option to create shared and nonshared client
- [x] create a separate interface for the client and functions
- [x] description of every public method
- [x] Proper exception handling, don't suppress the parent exception

### PR DESCRIPTION
**Pull request by dc-dream11**
… by connection object 3. varified exception handling

### Summary

Core Code Changes

### Full changelog
1. Config handling by objects
2. Policy handling through config
3. Added Listeners for all the operations
4. Test cases added
5. Documentation updated

Fix #3

### CODE REVIEW

File: src/main/java/com/dream11/aerospike/config/AerospikeConnectOptions.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
+package com.dream11.aerospike.config;
+
+import com.typesafe.config.Optional;
+import lombok.Data;
+
+@Data
+public class AerospikeConnectOptions {
```
Comment (akshaypatidar1999) [inline src/main/java/com/dream11/aerospike/config/AerospikeConnectOptions.java:14]: we should have `username`, `password` fields also

File: src/main/java/com/dream11/aerospike/factory/AerospikeClientFactoryImpl.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+  }
+
+  @Override
+  public AerospikeClient getClient(Vertx vertx, AerospikeConnectOptions config) {
+    ClientPolicy clientPolicy = PolicyUtil.getClientPolicy();
+    return getClient(vertx, clientPolicy, config);
+  }
+
+  @Override
+  public AerospikeClient getClient(Vertx vertx, ClientPolicy clientPolicy, AerospikeConnectOptions config) {
```
Comment (akshaypatidar1999) [inline src/main/java/com/dream11/aerospike/factory/AerospikeClientFactoryImpl.java]: instead of using both `ClientPolicy` and `AerospikeConnectOptions`, can we use only `AerospikeConnectOptions` by making `AerospikeConnectOptions extends ClientPolicy`

File: src/main/java/com/dream11/aerospike/factory/AerospikeClientFactoryImpl.java [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+import com.dream11.aerospike.client.AerospikeClientImpl;
+import com.dream11.aerospike.config.AerospikeConnectOptions;
+import com.dream11.aerospike.util.PolicyUtil;
+import com.dream11.aerospike.util.SharedDataUtils;
+import io.vertx.core.*;
+import lombok.extern.slf4j.Slf4j;
+
+
+@Slf4j
+public class AerospikeClientFactoryImpl implements AerospikeClientFactory {
```
Comment (akshaypatidar1999) [inline src/main/java/com/dream11/aerospike/factory/AerospikeClientFactoryImpl.java]: Can we get rid of this class and do all this is `AerospikeClientImpl.java` itself

File: src/main/java/com/dream11/aerospike/config/AerospikeConnectOptions.java [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+    static final String DEFAULT_HOST = "localhost";
+    static final int DEFAULT_PORT = 3000;
+    static final int DEFAULT_EVENT_LOOP_SIZE = 2*Runtime.getRuntime().availableProcessors();
+    static final int DEFAULT_MAX_COMMANDS_IN_PROCESS = 100;
+    static final int DEFAULT_WRITE_TIMEOUT = 2000;
+    static final int DEFAULT_READ_TIMEOUT = 1500;
+    static final int DEFAULT_TEND_INTERVAL = 1000;
+    static final int DEFAULT_MAX_CONNS_PER_NODE = DEFAULT_MAX_COMMANDS_IN_PROCESS * DEFAULT_EVENT_LOOP_SIZE;
+
+    private String hosts = DEFAULT_HOST;
```
Comment (akshaypatidar1999) [inline src/main/java/com/dream11/aerospike/config/AerospikeConnectOptions.java]: we should write `Fluent` Setters

File: src/main/java/com/dream11/aerospike/client/AerospikeClientImpl.java [hunk 5]
```diff
@@ -0,0 +1,343 @@
...
+      try {
+        handler.handle((Promise<T>)promise);
+      } catch (AerospikeException e) {
+        promise.fail(e);
+      }
+    }, result -> resultHandler.handle((AsyncResult<T>) result));
+  }
+
+  /**
+   * Determine if we are ready to talk to the database server cluster.
```
Comment (kkaran097) [inline src/main/java/com/dream11/aerospike/client/AerospikeClientImpl.java]: I think we should keep the documentation about the method and its parameters in the interface itself. In the implementation, we should only put details of implementation.

**Review by akshaypatidar1999 — APPROVED** [review]

**Review by kkaran097 — APPROVED** [review]

**Review by srijan02420 — APPROVED** [review]
